"""changed name of user id to uid

Revision ID: db1ba5dde752
Revises: faa895b5726d
Create Date: 2025-05-03 01:37:23.599768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db1ba5dde752'
down_revision: Union[str, None] = 'faa895b5726d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.UUID(), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
